using System.Linq;
using CUE4Parse.GameTypes.SMG.UE4.Assets.Objects;
using CUE4Parse.UE4.Assets.Exports.SkeletalMesh;
using CUE4Parse.UE4.Objects.Core.Math;
using CUE4Parse.UE4.Readers;
using CUE4Parse.UE4.Versions;
using Newtonsoft.Json;

namespace CUE4Parse.UE4.Assets.Exports.Animation;

public class FMorphTargetLODModel
{
    /** vertex data for a single LOD morph mesh */
    [JsonIgnore] public FMorphTargetDelta[] Vertices;
    /** number of original verts in the base mesh */
    public int NumBaseMeshVerts;
    /** list of sections this morph is used */
    public int[] SectionIndices;
    /** Is this LOD generated by reduction setting */
    public bool bGeneratedByEngine;
    /* The source filename use to import this morph target. If source is empty this morph target was import with the LOD geometry. */
    public string? SourceFilename;

    public FMorphTargetLODModel()
    {
        Vertices = [];
        NumBaseMeshVerts = 0;
        SectionIndices = [];
        bGeneratedByEngine = false;
    }

    public FMorphTargetLODModel(FArchive Ar)
    {
        if (FEditorObjectVersion.Get(Ar) < FEditorObjectVersion.Type.AddedMorphTargetSectionIndices)
        {
            Vertices = Ar.ReadArray(() => new FMorphTargetDelta(Ar));
            NumBaseMeshVerts = Ar.Read<int>();
            bGeneratedByEngine = false;
        }
        else if (FFortniteMainBranchObjectVersion.Get(Ar) < FFortniteMainBranchObjectVersion.Type.SaveGeneratedMorphTargetByEngine)
        {
            Vertices = Ar.ReadArray(() => new FMorphTargetDelta(Ar));
            NumBaseMeshVerts = Ar.Read<int>();
            SectionIndices = Ar.ReadArray<int>();
            bGeneratedByEngine = false;
        }
        else
        {
            if (Ar.Game is EGame.GAME_TheCastingofFrankStone or EGame.GAME_TheQuarry)
            {
                Ar.Position += 4; // NumVertices
                NumBaseMeshVerts = 1;
                Vertices = [];
                SectionIndices = Ar.ReadArray<int>();
                bGeneratedByEngine = Ar.ReadBoolean();
                return;
            }

            if (Ar.Game is EGame.GAME_DarkPicturesAnthologyHouseOfAshes or EGame.GAME_DarkPicturesAnthologyTheDevilinMe or
                EGame.GAME_DarkPicturesAnthologyManofMedan or EGame.GAME_DarkPicturesAnthologyLittleHope)
            {
                Vertices = FDPAMorphTargetDeltaBatchData.ProcessDPAMorphTargetDeltas(Ar);
                SectionIndices = Ar.ReadArray<int>();
                bGeneratedByEngine = Ar.ReadBoolean();
                return;
            }

            if (Ar.Game is EGame.GAME_RocoKingdomWorld)
            {
                var buffer = Ar.ReadArray<ulong>();
                Vertices = new FMorphTargetDelta[buffer.Length];
                for (int i = 0; i < buffer.Length; i++)
                {
                    ulong v = buffer[i];
                    var pos = (uint) (v & 0xFFFFFF);
                    var tan = (uint) ((v >> 24) & 0x1FFFF);
                    var vert = (uint) (v >> 45);
                    var posvec = new FVector((sbyte) (pos & 0xff), (sbyte) ((pos >> 8) & 0xff), (sbyte) ((pos >> 16) & 0xff)) / 127.5f;
                    var tanvec = new FVector((sbyte) (tan & 0x7f), (sbyte) ((tan >> 7) & 0x7f), (sbyte) ((tan >> 14) & 0x7f)) / 63.5f;
                    Vertices[i] = new FMorphTargetDelta(posvec, tanvec, vert);
                }
                NumBaseMeshVerts = Ar.Read<int>();
                SectionIndices = Ar.ReadArray<int>();
                bGeneratedByEngine = Ar.ReadBoolean();
                return;
            }

            var bVerticesAreStrippedForCookedBuilds = false;
            if (FUE5SpecialProjectStreamObjectVersion.Get(Ar) >= FUE5SpecialProjectStreamObjectVersion.Type.StripMorphTargetSourceDataForCookedBuilds)
            {
                // Strip source morph data for cooked build if targets don't include mobile. Mobile uses CPU morphing which needs the source morph data.
                bVerticesAreStrippedForCookedBuilds = Ar.ReadBoolean();
            }

            if (bVerticesAreStrippedForCookedBuilds)
            {
                Ar.Position += 4; // NumVertices
                Vertices = [];
            }
            else
            {
                Vertices = Ar.ReadArray(() => new FMorphTargetDelta(Ar));
            }

            NumBaseMeshVerts = Ar.Read<int>();
            SectionIndices = Ar.ReadArray<int>();
            bGeneratedByEngine = Ar.ReadBoolean();
        }

        if (FFortniteMainBranchObjectVersion.Get(Ar) >= FFortniteMainBranchObjectVersion.Type.MorphTargetCustomImport)
        {
            SourceFilename = Ar.ReadFString();
        }
    }

    public FMorphTargetLODModel(FMorphTargetVertexInfoBuffers buffer, int index, int[] sectionIndices)
    {
        var batchStartOffsetPerMorph = buffer.BatchStartOffsetPerMorph[index];
        var batchesPerMorph = buffer.BatchesPerMorph[index];
        var posPrecision = buffer.PositionPrecision;
        var tanPrecision = buffer.TangentZPrecision;

        var size = 0;
        for (var j = 0; j < batchesPerMorph; j++)
        {
            var batch = buffer.MorphData[batchStartOffsetPerMorph + j];
            size += (int)batch.NumElements;
        }

        Vertices = new FMorphTargetDelta[size];
        NumBaseMeshVerts = size;
        SectionIndices = sectionIndices;
        bGeneratedByEngine = false;

        var k = 0;
        for (var j = 0; j < batchesPerMorph; j++)
        {
            var batch = buffer.MorphData[batchStartOffsetPerMorph + j];
            var posMin = batch.PositionMin;
            var tanMin = batch.TangentZMin;

            foreach (var delta in batch.QuantizedDelta)
            {
                var pos = new FVector((posMin.X + delta.Position.X) * posPrecision,
                    (posMin.Y + delta.Position.Y) * posPrecision, (posMin.Z + delta.Position.Z) * posPrecision);
                var tan = new FVector((tanMin.X + delta.TangentZ.X) * tanPrecision,
                    (tanMin.Y + delta.TangentZ.Y) * tanPrecision, (tanMin.Z + delta.TangentZ.Z) * tanPrecision);
                Vertices[k++] = new FMorphTargetDelta(pos, tan, delta.Index);
            }
        }
    }

    public FMorphTargetLODModel(int[] sectionIndices, FDeltaBatchHeader[] batchHeaders, uint[] compressedVertices, float positionPrecision, float tangentZPrecision)
    {
        SectionIndices = sectionIndices;
        bGeneratedByEngine = false;
        
        var numDeltas = batchHeaders.Sum(header => (int)header.NumElements);
        
        Vertices = new FMorphTargetDelta[numDeltas];
        NumBaseMeshVerts = numDeltas;

        var index = 0;
        using var reader = new FDwordBitReader(compressedVertices);

        foreach (var header in batchHeaders)
        {
            for (var elementIndex = 0; elementIndex < header.NumElements; elementIndex++)
            {
                Vertices[index++] = DecodeMorphTargetDelta(header, reader, (uint)elementIndex, positionPrecision, tangentZPrecision);
            }
        }
    }

    private FMorphTargetDelta DecodeMorphTargetDelta(FDeltaBatchHeader header, FDwordBitReader reader, uint localIndex, float positionPrecision, float tangentZPrecision)
    {
        var sourceIdx = reader.GetBits((uint)header.IndexBits) + header.IndexMin + localIndex;
        var positionDelta = new FVector(
            ((int)reader.GetBits((uint)header.PositionBits.X) + header.PositionMin.X) * positionPrecision,
            ((int)reader.GetBits((uint)header.PositionBits.Y) + header.PositionMin.Y) * positionPrecision,
            ((int)reader.GetBits((uint)header.PositionBits.Z) + header.PositionMin.Z) * positionPrecision);

        var tangentZDelta = new FVector();
        if (header.bTangents)
        {
            tangentZDelta = new FVector(
                ((int)reader.GetBits((uint)header.TangentZBits.X) + header.TangentZMin.X) * tangentZPrecision,
                ((int)reader.GetBits((uint)header.TangentZBits.Y) + header.TangentZMin.Y) * tangentZPrecision,
                ((int)reader.GetBits((uint)header.TangentZBits.Z) + header.TangentZMin.Z) * tangentZPrecision);
        }
        
        return new FMorphTargetDelta(positionDelta, tangentZDelta, sourceIdx);
    }
}
