using CUE4Parse.UE4.Assets.Exports.NavigationSystem;
using CUE4Parse.UE4.Assets.Readers;
using CUE4Parse.UE4.Versions;

namespace CUE4Parse.UE4.Assets.Exports.Actor;

public class AActor : UObject
{
    public bool bIsCooked;
    public string? ActorLabel;
    public FActorInstanceGuid? ActorInstanceGuid;

    public override void Deserialize(FAssetArchive Ar, long validPos)
    {
        base.Deserialize(Ar, validPos);

        // not sure why, but very rarely it overreads for CDO, maybe related to SparseClassDataStructSerialization
        // doesn't matter so return early in this case
        if (Ar.Position >= validPos) return;
        if (Ar.Game == EGame.GAME_WorldofJadeDynasty) Ar.Position += 24;
        if (FUE5SpecialProjectStreamObjectVersion.Get(Ar) >= FUE5SpecialProjectStreamObjectVersion.Type.SerializeActorLabelInCookedBuilds)
        {
            bIsCooked = Ar.ReadBoolean();
            if (bIsCooked)
                ActorLabel = Ar.ReadFString();
        }

        if (FFortniteMainBranchObjectVersion.Get(Ar) >= FFortniteMainBranchObjectVersion.Type.LevelInstanceStaticLightingSupport)
        {
            ActorInstanceGuid = new FActorInstanceGuid(Ar);
        }
    }
}

public class AAIController : AController;
public class AARActor : AActor;
public class AAROriginActor : AActor;
public class AARPassthroughManager : AActor;
public class AARSharedWorldGameMode : AGameMode;
public class AARSharedWorldGameState : AGameState;
public class AARSharedWorldPlayerController : APlayerController;
public class AARSkyLight : ASkyLight;
public class AAbstractNavData : ANavigationData;
public class AActorModifierCoreSharedActor : AActor;
public class AAmbientSound : AActor;
public class AAnimationEditorPreviewActor : AActor;
public class AAnimationThumbnailSkeletalMeshActor : ASkeletalMeshActor;
public class AArchVisCharacter : ACharacter;
public class AAtmosphericFog : AInfo;
public class AAudioVolume : AVolume;
public class AAvaAnimationActor : AAvaSequencePlaybackActor;
public class AAvaCineCameraActor : ACineCameraActor;
public class AAvaClonerActor : ACEClonerActor;
public class AAvaEffectorActor : ACEEffectorActor;
public class AAvaNullActor : AActor;
public class AAvaPostProcessVolume : APostProcessVolume;
public class AAvaScene : AActor;
public class AAvaSequencePlaybackActor : AActor;
public class AAvaShapeActor : AActor;
public class AAvaSplineActor : AActor;
public class AAvaTestDynamicMeshActor : AActor;
public class AAvaTestStaticMeshActor : AActor;
public class AAvaTextActor : AActor;
public class AAvaToolboxShapeActor : AAvaShapeActor;
public class AAvaTransitionBehaviorActor : AActor;
public class AAvaTransitionPreviewManager : AActor;
public class AAvaViewportCameraActor : ACameraActor;
public class AAvaViewportDataActor : AActor;
public class AAvalancheText3DActor : AAvaTextActor;
public class ABandwidthTestActor : AActor;
public class ABaseTransformGizmo : AActor;
public class ABlockingVolume : AVolume;
public class ABlutilityActor : APlacedEditorUtilityBase;
public class ABoxReflectionCapture : AReflectionCapture;
public class ABrush : AActor;
public class ABrushShape : ABrush;
public class ACEClonerActor : AActor;
public class ACEEffectorActor : AActor;
public class ACableActor : AActor;
public class ACameraActor : AActor;
public class ACameraBlockingVolume : AVolume;
public class ACameraCalibrationCheckerboard : AActor;
public class ACameraRig_Crane : AActor;
public class ACameraRig_Rail : AActor;
public class ACameraShakeSourceActor : AActor;
public class AChaosCacheManager : AActor;
public class AChaosCachePlayer : AChaosCacheManager;
public class AChaosSolverActor : AActor;
public class AChaosVDParticleActor : AActor;
public class AChaosVDSceneQueryDataContainer : AActor;
public class AChaosVDSolverInfoActor : AActor;
public class ACharacter : APawn;
public class ACineCameraActor : ACameraActor;
public class ACineCameraAttachMount : AActor;
public class ACineCameraRigRail : ACameraRig_Rail;
public class AClusterUnionActor : AActor;
public class AColorCorrectRegion : AActor;
public class AColorCorrectRegion_C : AColorCorrectionRegion;
public class AColorCorrectWindow : AColorCorrectionWindow;
public class AColorCorrectionRegion : AColorCorrectRegion;
public class AColorCorrectionWindow : AColorCorrectRegion;
public class ACombinedTransformGizmoActor : AGizmoActor;
public class ACompositingCaptureBase : ACompositingElement;
public class ACompositingElement : AComposurePipelineBaseActor;
public class AComposureCompShotElement : ACompositingElement;
public class AComposurePipelineBaseActor : AActor;
public class AConcertClientDesktopPresenceActor : AConcertClientPresenceActor;
public class AConcertClientPresenceActor : AActor;
public class AConcertClientVRPresenceActor : AConcertClientPresenceActor;
public class AConstraintsActor : AActor;
public class AControlPointMeshActor : AActor;
public class AControlRigControlActor : AActor;
public class AControlRigGizmoActor : AControlRigShapeActor;
public class AControlRigShapeActor : AActor;
public class AController : AActor;
public class ACullDistanceVolume : AVolume;
public class ADataflowActor : AActor;
public class ADatasmithAreaLightActor : AActor;
public class ADatasmithImportedSequencesActor : AActor;
public class ADatasmithSceneActor : AActor;
public class ADebugCameraController : APlayerController;
public class ADebugCameraHUD : AHUD;
public class ADefaultPawn : APawn;
public class ADefaultPhysicsVolume : APhysicsVolume;
public class ADetourCrowdAIController : AAIController;
public class ADirectionalLight : ALight;
public class ADirectionalLightMovable : ADirectionalLight;
public class ADirectionalLightStatic : ADirectionalLight;
public class ADirectionalLightStationary : ADirectionalLight;
public class ADisplayClusterChromakeyCardActor : ADisplayClusterLightCardActor;
public class ADisplayClusterLightCardActor : AActor;
public class ADisplayClusterRootActor : AActor;
public class ADisplayClusterTestPatternsActor : AActor;
public class ADocumentationActor : AActor;
public class ADynamicBlockingVolume : ABlockingVolume;
public class ADynamicMeshActor : AActor;
public class ADynamicPhysicsVolume : APhysicsVolume;
public class ADynamicTriggerVolume : ATriggerVolume;
public class AEQSTestingPawn : ACharacter;
public class AEditorAutomationActor : AEditorUtilityActor;
public class AEditorFunctionalTest : AFunctionalTest;
public class AEditorScreenshotFunctionalTest : AScreenshotFunctionalTest;
public class AEditorUtilityActor : AActor;
public class AEditorUtilityCamera : ACameraActor;
public class AEmitter : AActor;
public class AEmitterCameraLensEffectBase : AEmitter;
public class AEmitterSpawnable : AEmitter;
public class AExponentialHeightFog : AInfo;
public class AFieldSystemActor : AActor;
public class AFloatingText : AActor;
public class AFullScreenUserWidgetActor : AInfo;
public class AFunctionalAITest : AFunctionalAITestBase;
public class AFunctionalAITestBase : AFunctionalTest;
public class AFunctionalTest : AActor;
public class AFunctionalTestGameMode : AGameModeBase;
public class AFunctionalTestLevelScript : ALevelScriptActor;
public class AFunctionalUIScreenshotTest : AScreenshotFunctionalTestBase;
public class AGameMode : AGameModeBase;
public class AGameModeBase : AInfo;
public class AGameNetworkManager : AInfo;
public class AGameSession : AInfo;
public class AGameState : AGameStateBase;
public class AGameStateBase : AInfo;
public class AGameplayCameraActor : AActor;
public class AGameplayCameraSystemActor : AActor;
public class AGameplayDebuggerCategoryReplicator : AActor;
public class AGameplayDebuggerPlayerManager : AActor;
public class AGeneratedDynamicMeshActor : ADynamicMeshActor;
public class AGeneratedMeshAreaLight : ASpotLight;
public class AGeometryCacheActor : AActor;
public class AGeometryCollectionActor : AActor;
public class AGeometryCollectionDebugDrawActor : AActor;
public class AGeometryCollectionISMPoolActor : AActor;
public class AGeometryCollectionRenderLevelSetActor : AActor;
public class AGeometryMaskCanvasActor : AActor;
public class AGizmoActor : AInternalToolFrameworkActor;
public class AGridPathAIController : AAIController;
public class AGroomActor : AActor;
public class AGroupActor : AActor;
public class AHUD : AActor;
public class AHairStrandsActor : AGroomActor;
public class AHeterogeneousVolume : AInfo;
public class AHierarchicalLODVolume : AVolume;
public class AISMPartitionActor : APartitionActor;
public class AInfo : AActor;
public class AInstancedPlacementPartitionActor : AISMPartitionActor;
public class AInteractiveFoliageActor : AStaticMeshActor;
public class AInternalToolFrameworkActor : AActor;
public class AInterpActor : AStaticMeshActor;
public class AIntervalGizmoActor : AGizmoActor;
public class AKillZVolume : APhysicsVolume;
public class ALODActor : AActor;
public class ALandmassActor : AActor;
public class ALandmassErosionBrushBase : ALandscapeBlueprintBrushBase;
public class ALandmassManagerBase : ALandscapeBlueprintBrushBase;
public class ALandscapeBlueprintBrush : ALandscapeBlueprintBrushBase;
public class ALandscapeBlueprintBrushBase : AActor;
public class ALandscapeBlueprintCustomBrush : ALandscapeBlueprintBrush;
public class ALandscapeGizmoActiveActor : ALandscapeGizmoActor;
public class ALandscapeGizmoActor : AActor;
public class ALandscapeMeshProxyActor : AActor;
public class ALandscapePlaceholder : AActor;
public class ALandscapeSplineActor : AActor;
public class ALandscapeSplineMeshesActor : APartitionActor;
public class ALevelBounds : AActor;
public class ALevelInstanceEditorInstanceActor : AActor;
public class ALevelInstancePivot : AActor;
public class ALevelScriptActor : AActor;
public class ALevelSequenceActor : AActor;
public class ALevelSequenceMediaController : AActor;
public class ALevelStreamingVolume : AVolume;
public class ALevelVariantSetsActor : AActor;
public class ALight : AActor;
public class ALightWeightInstanceManager : AActor;
public class ALightWeightInstanceStaticMeshManager : ALightWeightInstanceManager;
public class ALightmassCharacterIndirectDetailVolume : AVolume;
public class ALightmassImportanceVolume : AVolume;
public class ALightmassPortal : AActor;
public class ALocalFogVolume : AInfo;
public class ALocationVolume : AVolume;
public class AManipulator : AActor;
public class AMaterialInstanceActor : AActor;
public class AMediaBundleActorBase : AActor;
public class AMediaPlate : AActor;
public class AMeshMergeCullingVolume : AVolume;
public class AMoviePipelineFunctionalTestBase : AFunctionalTest;
public class AMoviePipelineGameMode : AGameModeBase;
public class ANavLinkProxy : AActor;
public class ANavMeshBoundsVolume : AVolume;
public class ANavModifierVolume : AVolume;
public class ANavSystemConfigOverride : AActor;
public class ANavigationDataChunkActor : APartitionActor;
public class ANavigationGraph : ANavigationData;
public class ANavigationGraphNode : AActor;
public class ANavigationObjectBase : AActor;
public class ANavigationTestingActor : AActor;
public class ANiagaraActor : AActor;
public class ANiagaraLensEffectBase : ANiagaraActor;
public class ANiagaraPerfBaselineActor : AActor;
public class ANiagaraPreviewBase : AActor;
public class ANiagaraPreviewGrid : AActor;
public class ANote : AActor;
public class AOctaneLightmassSettingsActor : AInfo;
public class AOctaneOrbxActor : AActor;
public class AOctaneRenderTargetActor : AActor;
public class AOctaneScreenshotFunctionalTest : AFunctionalTest;
public class AOnlineBeacon : AActor;
public class AOnlineBeaconClient : AOnlineBeacon;
public class AOnlineBeaconHost : AOnlineBeacon;
public class AOnlineBeaconHostObject : AActor;
public class APackedLevelActor : ALevelInstance;
public class APackedLevelInstance : APackedLevelActor;
public class APainCausingVolume : APhysicsVolume;
public class APaperCharacter : ACharacter;
public class APaperFlipbookActor : AActor;
public class APaperGroupedSpriteActor : AActor;
public class APaperRenderActor : APaperSpriteActor;
public class APaperSpriteActor : AActor;
public class APaperTerrainActor : AActor;
public class APaperTileMapActor : AActor;
public class AParticleEventManager : AActor;
public class APartitionActor : AActor;
public class APartyBeaconClient : AOnlineBeaconClient;
public class APartyBeaconHost : AOnlineBeaconHostObject;
public class APawn : AActor;
public class APhasedAutomationActorBase : AActor;
public class APhysicsActor : AStaticMeshActor;
public class APhysicsBSJointActor : APhysicsConstraintActor;
public class APhysicsConstraintActor : ARigidBodyBase;
public class APhysicsHingeActor : APhysicsConstraintActor;
public class APhysicsPrismaticActor : APhysicsConstraintActor;
public class APhysicsThruster : ARigidBodyBase;
public class APhysicsVolume : AVolume;
public class APivotTransformGizmo : ABaseTransformGizmo;
public class APlacedEditorUtilityBase : AActor;
public class APlanarReflection : ASceneCapture;
public class APlaneReflectionCapture : AReflectionCapture;
public class APlayerCameraManager : AActor;
public class APlayerController : AController;
public class APlayerStart : ANavigationObjectBase;
public class APlayerStartPIE : APlayerStart;
public class APlayerState : AInfo;
public class APointLight : ALight;
public class APointLightMovable : APointLight;
public class APointLightStatic : APointLight;
public class APointLightStationary : APointLight;
public class APostProcessVolume : AVolume;
public class APrecomputedVisibilityOverrideVolume : AVolume;
public class APrecomputedVisibilityVolume : AVolume;
public class APreviewGeometryActor : AInternalToolFrameworkActor;
public class APreviewMeshActor : AInternalToolFrameworkActor;
public class AProceduralFoliageActor : AProceduralFoliageVolume;
public class AProceduralFoliageBlockingVolume : AVolume;
public class AProceduralFoliageVolume : AVolume;
public class APropertyEditorTestActor : AActor;
public class ARB_ConstraintActor : APhysicsConstraintActor;
public class ARB_Thruster : APhysicsThruster;
public class ARadialForceActor : ARigidBodyBase;
public class ARectLight : ALight;
public class AReflectionCapture : AActor;
public class ARemoteControlPresetActor : AActor;
public class AReplicatedLevelSequenceActor : ALevelSequenceActor;
public class AResonanceAudioDirectivityVisualizer : AActor;
public class AReverbVolume : AAudioVolume;
public class AReverbVolumeToggleable : AAudioVolume;
public class ARigidBodyBase : AActor;
public class ARuntimeVirtualTextureVolume : AActor;
public class ASVGActor : ASVGDynamicMeshesContainerActor;
public class ASVGBakedActor : AActor;
public class ASVGDynamicMeshesContainerActor : AActor;
public class ASVGJoinedShapesActor : ASVGDynamicMeshesContainerActor;
public class ASVGShapeActor : ASVGDynamicMeshesContainerActor;
public class ASVGShapesParentActor : ASVGDynamicMeshesContainerActor;
public class ASceneCapture : AActor;
public class ASceneCapture2D : ASceneCapture;
public class ASceneCaptureCube : ASceneCapture;
public class AScreenshotFunctionalTest : AScreenshotFunctionalTestBase;
public class AScreenshotFunctionalTestBase : AFunctionalTest;
public class ASequenceRecorderGroup : AActor;
public class ASequencerKeyActor : AActor;
public class ASequencerMeshTrail : AActor;
public class AServerStatReplicator : AInfo;
public class AServerStreamingLevelsVisibility : AActor;
public class ASingleAnimSkeletalActor : ASkeletalMeshActor;
public class ASkeletalMeshActor : AActor;
public class ASkeletalPhysicsActor : ASkeletalMeshActor;
public class ASkyAtmosphere : AInfo;
public class ASkyLight : AInfo;
public class ASparseVolumeTextureViewer : AInfo;
public class ASpatialHashRuntimeGridInfo : AInfo;
public class ASpectatorBeaconClient : AOnlineBeaconClient;
public class ASpectatorBeaconHost : AOnlineBeaconHostObject;
public class ASpectatorPawn : ADefaultPawn;
public class ASphereReflectionCapture : AReflectionCapture;
public class ASplineMeshActor : AActor;
public class ASpotLight : ALight;
public class ASpotLightMovable : ASpotLight;
public class ASpotLightStatic : ASpotLight;
public class ASpotLightStationary : ASpotLight;
public class AStaticMeshActor : AActor;
public class ASwitchActor : AActor;
public class ATagCollectionModifierSharedActor : AActorModifierCoreSharedActor;
public class ATargetPoint : AActor;
public class ATemplateSequenceActor : AActor;
public class ATestBeaconClient : AOnlineBeaconClient;
public class ATestBeaconHost : AOnlineBeaconHostObject;
public class AText3DActor : AActor;
public class ATextRenderActor : AActor;
public class ATriggerBase : AActor;
public class ATriggerBox : ATriggerBase;
public class ATriggerCapsule : ATriggerBase;
public class ATriggerSphere : ATriggerBase;
public class ATriggerVolume : AVolume;
public class AVCamBaseActor : ACineCameraActor;
public class AVCamBaseActorWithPreset : AVCamBaseActor;
public class AVPBookmarkActor : AVPViewportTickableActorBase;
public class AVPCameraBase : ACineCameraActor;
public class AVPEditorTickableActorBase : AVPViewportTickableActorBase;
public class AVPGameMode : AGameMode;
public class AVPPassthroughPostProcessVolume : APostProcessVolume;
public class AVPRootActor : AActor;
public class AVPTransientEditorTickableActorBase : AVPEditorTickableActorBase;
public class AVPViewportTickableActorBase : AActor;
public class AVREditorAvatarActor : AActor;
public class AVREditorBaseActor : AActor;
public class AVREditorDockableCameraWindow : AVREditorDockableWindow;
public class AVREditorDockableWindow : AVREditorFloatingUI;
public class AVREditorFloatingCameraUI : AVREditorFloatingUI;
public class AVREditorFloatingUI : AVREditorBaseActor;
public class AVREditorRadialFloatingUI : AVREditorBaseActor;
public class AVREditorTeleporter : AActor;
public class AVRTool : AVPTransientEditorTickableActorBase;
public class AVariantManagerTestActor : AActor;
public class AVectorFieldVolume : AActor;
public class AVisualLoggerCameraController : ADebugCameraController;
public class AVisualLoggerFilterVolume : AVolume;
public class AVisualLoggerHUD : ADebugCameraHUD;
public class AVisualLoggerRenderingActor : AVisualLoggerRenderingActorBase;
public class AVisualLoggerRenderingActorBase : AActor;
public class AVolume : ABrush;
public class AVolumetricCloud : AInfo;
public class AVolumetricLightmapDensityVolume : AVolume;
public class AWindDirectionalSource : AInfo;
public class AWorldDataLayers : AInfo;
public class AWorldInfo : AWorldSettings;
public class AWorldPartitionHLOD : AActor;
public class AWorldPartitionMiniMap : AInfo;
public class AWorldPartitionMiniMapVolume : AVolume;
public class AWorldPartitionReplay : AActor;
public class AWorldPartitionVolume : AVolume;
public class AWorldSettings : AInfo
{
    public override void Deserialize(FAssetArchive Ar, long validPos)
    {
        if (Ar.Game == EGame.GAME_WorldofJadeDynasty) Ar.Position += 20;
        base.Deserialize(Ar, validPos);
    }
}
