namespace CUE4Parse.UE4.Wwise.Enums;

// Doesn't actually exist, but it's cleaner
public enum EAkPluginId : uint
{
    None,
    // Codecs
    BANK                                 = 0x00000001,
    PCM                                  = 0x00010001,
    ADPCM                                = 0x00020001,
    XMA                                  = 0x00030001,
    VORBIS                               = 0x00040001,
    WIIADPCM                             = 0x00050001,
    PCMEX                                = 0x00070001, // "Standard PCM WAV file parser for Wwise Authoring" (same as PCM with another codec)
    EXTERNAL_SOURCE                      = 0x00080001, // "unknown encoding" (.wem can be anything defined at runtime)
    XWMA                                 = 0x00090001,
    AAC                                  = 0x000A0001,
    FILE_PACKAGE                         = 0x000B0001, // "File package files generated by the File Packager utility."
    ATRAC9                               = 0x000C0001,
    VAG_HE_VAG                           = 0x000D0001,
    PROFILERCAPTURE                      = 0x000E0001, // "Profiler capture file (.prof)"
    ANALYSISFILE                         = 0x000F0001,
    MIDI                                 = 0x00100001, // .wmid (modified .mid)
    OPUSNX                               = 0x00110001, // originally just OPUS
    CAF                                  = 0x00120001, // unused?
    OPUS                                 = 0x00130001,
    OPUS_WEM                             = 0x00140001,
    OPUS_WEM1                            = 0x00150001, // "Memory stats file as written through AK::MemoryMgr::DumpToFile()"
    SONY360                              = 0x00160001,

    // Built-in plugins
    AkFxSrcSineSource                    = 0x00640002,
    AkFxSrcSilenceSource                 = 0x00650002,
    AkToneSource                         = 0x00660002,
    AkParameterEQFX                      = 0x00690003,
    AkDelayFX                            = 0x006A0003,
    AkCompressorFX                       = 0x006C0003,
    AkExpanderFX                         = 0x006D0003,
    AkPeakLimiterFX                      = 0x006E0003,

    AkMatrixReverbFX                     = 0x00730003,
    AkSoundSeedImpactFX                  = 0x00740003,
    AkRoomVerbFX                         = 0x00760003,
    AkSoundSeedWind                      = 0x00770002,
    AkSoundSeedWoosh                     = 0x00780002,
    AkFlangerFX                          = 0x007D0003,
    AkGuitarDistortionFX                 = 0x007E0003,
    AkConvolutionReverbFX                = 0x007F0003,

    AkMeterFX                            = 0x00810003,
    AkTimeStretchFX                      = 0x00820003,
    AkTremoloFX                          = 0x00830003,
    AkRecorderFX                         = 0x00840003,
    AkStereoDelayFX                      = 0x00870003,
    AkPitchShifterFX                     = 0x00880003,
    AkHarmonizerFX                       = 0x008A0003,
    AkGainFX                             = 0x008B0003,

    AkSynthOne                           = 0x00940002,

    ASIOSink                             = 0x00A80007,
    AkReflectFX                          = 0x00AB0003,
    AkRouterMixer                        = 0x00AC0006,

    // Built-in sinks
    SystemSink                           = 0x00AE0007,
    DVRByPassSink                        = 0x00AF0007,
    CommunicationSink                    = 0x00B00007,
    ControllerHeadphonesSink             = 0x00B10007,
    VoiceSink                            = 0x00B20007,
    ControllerSpeakerSink                = 0x00B30007,
    AuxiliarySink                        = 0x00B40007,
    NoOutputSink                         = 0x00B50007,
    RemoteSystemSink                     = 0x00B60007,

    AkSoundSeedGrain                     = 0x00B70002,
    AkImpacterSource                     = 0x00B80002,
    MasteringSuiteFX                     = 0x00BA0003,
    Ak3DAudioBedMixerFX                  = 0x00BE0003,
    AkChannelRouterFX                    = 0x00BF0003,

    AkSidechainSendFX                    = 0x00C10003,
    AkSidechainRecvFX                    = 0x00C20003,
    AkMultibandMeterFX                   = 0x00C40003,
    AkRecorder_ADM                       = 0x00C60003,
    AkAudioInputSource                   = 0x00C80002,
    ASIOSource                           = 0x00CC0002,

    AkMotionGeneratorSource              = 0x01950002,
    AkMotionGeneratorMotionSource        = 0x01950005,
    AkMotionSourceSource                 = 0x01990002,
    AkMotionSource                       = 0x01990005,
    AkMotionSink                         = 0x01FB0007,

    AkSystemOutputMeta                   = 0x03840009,

    // Third-party plugins
    AudioSpectrumFX                      = 0x002E2FD3,
    AuroHeadphoneFX                      = 0x044C1073,

    bnsRadio                             = 0x039B2FD3,

    CrankcaseAudioREVModelPlayer         = 0x01A01052,

    IgniterLive                          = 0x005110D2,
    IgniterLiveSynth                     = 0x005210D2,

    iZHybridReverbFX                     = 0x00021033,
    iZTrashDistortionFX                  = 0x00031033,
    iZTrashDelayFX                       = 0x00041033,
    iZTrashDynamicsFX                    = 0x00051033,
    iZTrashFiltersFX                     = 0x00061033,
    iZTrashBoxModelerFX                  = 0x00071033,
    iZTrashMultibandDistortionFX         = 0x00091033,

    // Mindseye
    AudioDataPassbackFX                  = 0x234C0403,
    BarbDelayFX                          = 0x352A0403,
    BarbRecorderFX                       = 0x7C550403,
    DrunkPMSource                        = 0x00030A32,

    McDSPLimiterFX                       = 0x00671003,
    McDSPFutzBoxFX                       = 0x006E1003,

    MsSpatialSink                        = 0x00aa1137,

    // MetaXRAudio
    OculusEndpointSink                   = 0x009410a7,
    OculusEndpointMetadata               = 0x3d6a10a9,
    OculusEndpointExperimentalMetadata   = 0x3d6b10a9,

    ResonanceAudioRendererFX             = 0x00641103,
    ResonanceAudioRoomEffectMixer        = 0x00C81106,
    ResonanceAudioRoomEffectFX           = 0x00C91103,

    SpeechEngine                         = 0x00011382,

    // TencentGME
    TencentGMESendFX                     = 0x232C1213,
    TencentGMESource                     = 0x23291212,
    TencentGMEReceiveSource              = 0x232B1212,
    TencentGMESessionFX                  = 0x232D1212,
}
