using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace CUE4Parse.UE4.Objects.Chaos.GeometryCollection;

[JsonConverter(typeof(StringEnumConverter))]
public enum EManagedArrayType : byte
{
    None,
    Vector,
    IntVector,
    Vector2D,
    LinearColor,
    Int32,
    Bool,
    Transform,
    String,
    Float,
    Quat,
    BoneNode,
    MeshSection,
    Box,
    IntArray,
    Guid,
    UInt8,
    VectorArrayPointer,
    VectorArrayUniquePointer,
    FImplicitObject3Pointer,
    FImplicitObject3UniquePointer,
    FImplicitObject3SerializablePtr,
    FBVHParticlesFloat3Pointer,
    FBVHParticlesFloat3UniquePointer,
    TPBDRigidParticleHandle3fPtr,
    TPBDGeometryCollectionParticleHandle3fPtr,
    TGeometryParticle3fUniquePtr,
    FImplicitObject3ThreadSafeSharedPointer,
    FImplicitObject3SharedPointer,
    TPBDRigidClusteredParticleHandle3fPtr,
    FConvexUniquePtr,
    Vector2DArray,
    Double,
    IntVector4,
    Vector3d,
    IntVector2,
    IntVector2Array,
    Int32Array,
    FloatArray,
    Vector4f,
    FVectorArray,
    TPBDRigidParticle3fUniquePtr,
    FImplicitObjectRefCountedPtr,
    FConvexRefCountedPtr,
    Transform3f,
    IntVector3Array,
    Vector4fArray,
    PMatrix33d,
    PMatrix33dArray,
    FVector3fNestedArray,
    UintVector2,
    UObjectArray,
    LinearCurve,
    Name,
    SoftObjectPath
}
