namespace CUE4Parse.UE4.Chaos.GeometryCollection;

public enum EManagedArrayType: byte
{
    FNoneType,
    FVectorType,
    FIntVectorType,
    FVector2DType,
    FLinearColorType,
    FInt32Type,
    FBoolType,
    FTransformType,
    FStringType,
    FFloatType,
    FQuatType,
    FBoneNodeType,
    FMeshSectionType,
    FBoxType,
    FIntArrayType,
    FGuidType,
    FUInt8Type,
    FVectorArrayPointerType,
    FVectorArrayUniquePointerType,
    FFImplicitObject3PointerType,
    FFImplicitObject3UniquePointerType,
    FFImplicitObject3SerializablePtrType,
    FFBVHParticlesFloat3PointerType,
    FFBVHParticlesFloat3UniquePointerType,
    FTPBDRigidParticleHandle3fPtrType,
    FTPBDGeometryCollectionParticleHandle3fPtrType,
    FTGeometryParticle3fUniquePtrType,
    FFImplicitObject3ThreadSafeSharedPointerType,
    FFImplicitObject3SharedPointerType,
    FTPBDRigidClusteredParticleHandle3fPtrType,
    FFConvexUniquePtrType,
    FVector2DArrayType,
    FDoubleType,
    FIntVector4Type,
    FVector3dType,
    FIntVector2Type,
    FIntVector2ArrayType,
    FInt32ArrayType,
    FFloatArrayType,
    FVector4fType,
    FFVectorArrayType,
    FTPBDRigidParticle3fUniquePtrType,

    // ue 5.4+
    FFImplicitObjectRefCountedPtrType,
    FConvexRefCountedPtrType,
    Transform3fType,
    IntVector3ArrayType,
    Vector4fArrayType,
}