namespace CUE4Parse.UE4.FMod.Enums;

public enum EFModStudioParameterType : uint
{
    FMOD_STUDIO_PARAMETER_GAME_CONTROLLED = 0x0,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE = 0x1,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE = 0x2,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION = 0x3,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION = 0x4,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION = 0x5,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION = 0x6,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED = 0x7,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED_ABSOLUTE = 0x8,
    FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE_NORMALIZED = 0x9,
    FMOD_STUDIO_PARAMETER_MAX = 0xa,
    FMOD_STUDIO_PARAMETER_FORCEINT = 0x10000
}
