namespace CUE4Parse.UE4.FMod.Enums;


/// <summary>
/// Tested games by FMOD version:
/// 
/// FMOD | Game(s)
/// -----|---------------
/// 0x33 | All is Dust
/// 0x3E | Interloper
/// 0x40 | Ancestory
/// 0x44 | Quanero VR
/// 0x4A | Quanero VR
/// 0x87 | Train Life - A Railway Simulator (UE 4.27)
/// 0x8E | Dispatch Demo (UE 4.27) | Militsioner (UE 5.3) | Deadly Days: Roadtrip Demo (UE 5.5) | Daimon Blades (UE 5.5) |
/// The Day Before (UE 5.2) | UNYIELDER (UE 5.3) | Firefighting Simulator Ignite (UE 5.4) | Ghostrunner2 (UE 4.27) |
/// Disney Epic Mickey Rebrushed Demo (UE 4.27) | GODBREAKERS (UE 5.4) | Ascend | Looking For Fael Demo | Tetherfall Demo |
/// Cave Game | Nikoderiko: The Magical World Demo | Stereo-Mix Demo | Gothic 1 Remake - Demo (Nyras Prologue) |
/// Vespera Bononia Demo | Always With You Demo | Steel Century Groove Demo | ShantyTown Demo | TerraTech Legion Demo |
/// Void Flesh Demo | Bullet Ballet | A.I.L.A Demo | Shepherd Knight Demo | Echoes of Mora Demo | Beat of Rebellion Demo |
/// Wrack Remake Demo | Poveglia Demo | Primal Echo Demo
/// 0x92 | Dead as Disco Demo (UE 5.5) | Rage Quit (UE 5.5) | Goldilock One: The Mists of Jakaira Demo | Stereo-Mix Demo |
/// 14:Overmind Demo | Underpacked! Demo | Dreadbone Demo | Lilith Demo | Groovity Demo | Skyfire Demo | LORT Demo |
/// SpongeBob SquarePants: Titans of the Tide Demo | Manairons Demo | Bus Bound Demo | Duskfade Demo | ASHGARD: Infinity Mask Demo
/// </summary>
public enum EFModVersion : int
{
    OLDEST_SUPPORTED_FILEVERSION = 0x2c,
    FILEVERSION_45 = 0x2d,
    FILEVERSION_47 = 0x2f,
    FILEVERSION_48 = 0x30,
    FILEVERSION_49 = 0x31,
    FILEVERSION_51 = 0x33,
    FILEVERSION_52 = 0x34,
    FILEVERSION_53 = 0x35,
    FILEVERSION_54 = 0x36,
    FILEVERSION_55 = 0x37,
    FILEVERSION_56 = 0x38,
    FILEVERSION_57 = 0x39,
    FILEVERSION_EVENTINSTRUMENT_CHANNELFORMAT_FIX = 0x3a,
    FILEVERSION_CHANNELLAYOUT = 0x3b,
    FILEVERSION_SUBEVENT_REMOVAL = 0x3c,
    FILEVERSION_EFFECT_BYPASS = 0x3d,
    FILEVERSION_TRANSITIONTIMELINE_LEADIN_LEADOUT = 0x3e,
    FILEVERSION_SPAWNINGINSTRUMENT_CHANNELFORMAT_FIX = 0x3f,
    FILEVERSION_COMPRESSOR_LINKED_PARAMETER = 0x40,
    FILEVERSION_TOPLEVEL_EVENT_COUNT = 0x41,
    FILEVERSION_BUS_POLYPHONY = 0x42,
    FILEVERSION_MULTIPLE_TRANSITION_CONDITIONS = 0x43,
    FILEVERSION_TRANSITIONTIMELINE_SKIP_UNUSED = 0x44,
    FILEVERSION_VCA_PROPERTYOWNER = 0x45,
    FILEVERSION_RESOURCE_LOADING_MODE = 0x46,
    FILEVERSION_INSTRUMENT_LEFT_TRIM = 0x47,
    FILEVERSION_INSTRUMENT_SEEK_PERCENT = 0x48,
    FILEVERSION_MASTERBUS_ROUTABLE = 0x49,
    FILEVERSION_SIDECHAINEFFECT_CHANNELLAYOUT = 0x4a,
    FILEVERSION_PROGRAMMERINSTRUMENT_CHANNELFORMAT_FIX = 0x4b,
    FILEVERSION_DEFAULT_CHANNELLAYOUT_FIX = 0x4c,
    FILEVERSION_SOUND_NAMES = 0x4d,
    FILEVERSION_EVENT_COOLDOWN = 0x4e,
    FILEVERSION_STEAL_QUIETEST = 0x4f,
    FILEVERSION_AUTOPITCH_AT_MINIMUM = 0x50,
    FILEVERSION_LOOSE_WAVEFORMS = 0x51,
    FILEVERSION_ASYMMETRIC_SEEK_SPEED = 0x52,
    FILEVERSION_ENVELOPEFOLLOWER_REMOVAL = 0x53,
    FILEVERSION_TIMELOCKED_INSTRUMENTS_FIX = 0x54,
    FILEVERSION_MODULATOR_PROPERTYOWNER = 0x55,
    FILEVERSION_INSTRUMENT_VOLUME_DOUBLE_FIX = 0x56,
    FILEVERSION_AHDSR_CURVE_SHAPE_FIX = 0x57,
    FILEVERSION_LOOPING_SOUND_IN_MULTISOUND_CUTOFF_FIX = 0x58,
    FILEVERSION_HASHDATA = 0x59,
    FILEVERSION_CONTROLLER_INPUT_REMOVAL = 0x5a,
    FILEVERSION_EFFECT_INPUT_LAYOUT_ON_BUS = 0x5b,
    FILEVERSION_BUS_MUTE = 0x5c,
    FILEVERSION_DELETE_INFO = 0x5d,
    FILEVERSION_SPAWN_RATE = 0x5e,
    FILEVERSION_MUTE_INFO = 0x5f,
    FILEVERSION_PARAMETERLAYOUTS_REMOVAL = 0x60,
    FILEVERSION_TOPLEVEL_EVENT_FLAG = 0x61,
    FILEVERSION_MODEL_REFRESH_LIST = 0x62,
    FILEVERSION_LOOSEWAVEFORMRESOURCE_FINGERPRINT = 0x63,
    FILEVERSION_SCATTER_PROPERTIES_ONLY_ON_MULTIINSTRUMENTS = 0x63,
    FILEVERSION_PERSISTENT_EVENT_FLAG = 0x64,
    FILEVERSION_GLOBAL_SEQUENTIAL_PLAY_MODE = 0x65,
    FILEVERSION_OVERLAP_SOURCE_DESTINATION_TRANSITION = 0x66,
    FILEVERSION_FOLLOW_TRANSITIONS_IN_TRANSITION = 0x67,
    FILEVERSION_SPAWNING_TRIGGERDELAY_REMOVAL = 0x68,
    FILEVERSION_STEPPED_CURVE_POINTS = 0x69,
    FILEVERSION_TRIGGERBOX_EXCLUDE_END = 0x6a,
    FILEVERSION_EVENT_TRACK_LIST = 0x6b,
    FILEVERSION_MIXERSTRIP_VCA_LIST = 0x6c,
    FILEVERSION_PARENT_EVENT_REMOVAL = 0x6d,
    FILEVERSION_EFFECT_SIDECHAIN_ENABLED = 0x6e,
    FILEVERSION_BUS_OBJECT_PANNER_INDEX = 0x6f,
    FILEVERSION_PARAMETERMODEL_FLAGS = 0x70,
    FILEVERSION_PARAMETERLAYOUT_FLAGS = 0x71,
    FILEVERSION_PARAMETER_READONLY = 0x72,
    FILEVERSION_BUILT_IN_PARAMETER_SPEED = 0x73,
    FILEVERSION_AHDSR_FINAL_VALUE = 0x74,
    FILEVERSION_AHDSR_TIME_MILLISECONDS = 0x75,
    FILEVERSION_PARAMETER_PUBLIC_IDS = 0x76,
    FILEVERSION_COMMAND_INSTRUMENTS = 0x77,
    FILEVERSION_PLATFORM_INFO = 0x78,
    FILEVERSION_RELATIVE_TRANSITION_OFFSET = 0x79,
    FILEVERSION_RELATIVE_TRANSITION_INVERT = 0x7a,
    FILEVERSION_TRANSITION_MAGNET = 0x7b,
    FILEVERSION_AUDIO_TABLE_MODE = 0x7c,
    FILEVERSION_RMS_SIDECHAIN = 0x7d,
    FILEVERSION_TRANSITION_FADE_OVERRIDES = 0x7e,
    FILEVERSION_TRANSITION_DATA_UPDATE = 0x7f,
    FILEVERSION_ADDITIONAL_COMMANDS = 0x80,
    FILEVERSION_SILENCE_INSTRUMENT = 0x81,
    FILEVERSION_CONDITIONAL_OPERATORS = 0x82,
    FILEVERSION_EVENT_TRIGGERED_INSTRUMENTS = 0x83,
    FILEVERSION_SUSTAIN_POINT_CONDITIONS = 0x84,
    FILEVERSION_QUANTIZED_SCATTERER = 0x85,
    FILEVERSION_UNUSED_PARAMETERS = 0x86,
    FILEVERSION_DISCRETE_PARAMETER_RANGE = 0x87,
    FILEVERSION_SIDECHAINEFFECT_LEVEL = 0x88,
    FILEVERSION_EVENT_ATTENUATION_RANGE = 0x89,
    FILEVERSION_SCATTERER_SPAWN_TOTAL_AUTOMATION = 0x8a,
    FILEVERSION_PARAMETER_LABELS = 0x8b,
    FILEVERSION_OUTPUT_PORTS = 0x8c,
    FILEVERSION_PARAMETER_LABELED_FLAG = 0x8d,
    FILEVERSION_SCATTERER_SPAWN_TOTAL_INF_FIX = 0x8e,
    FILEVERSION_SEEK_MODULATOR = 0x8f,
    FILEVERSION_MODULATOR_CLOCK_SOURCE = 0x90,
    FILEVERSION_SPECTRAL_SIDECHAIN_MODULATOR = 0x91,
    FILEVERSION_EFFECT_WET_DRY = 0x92,
    FILEVERSION_MAX = 0x93,

    NEWEST_SUPPORTED_FILEVERSION = 0x92,
    CURRENT_FILEVERSION = 0x92
}
