namespace CUE4Parse.UE4.FMod.Enums;

public enum EPortType : uint
{
    FMOD_PORT_TYPE_MUSIC = 0x0,
    FMOD_PORT_TYPE_COPYRIGHT_MUSIC = 0x1,
    FMOD_PORT_TYPE_VOICE = 0x2,
    FMOD_PORT_TYPE_CONTROLLER = 0x3,
    FMOD_PORT_TYPE_PERSONAL = 0x4,
    FMOD_PORT_TYPE_VIBRATION = 0x5,
    FMOD_PORT_TYPE_AUX = 0x6,
    FMOD_PORT_TYPE_PASSTHROUGH = 0x7,
    FMOD_PORT_TYPE_VR_VIBRATION = 0x8,
    FMOD_PORT_TYPE_MAX = 0x9,
    FMOD_PORT_TYPE_FORCEINT = 0x10000
};
