using CUE4Parse.UE4.Assets.Readers;
using CUE4Parse.UE4.Objects.UObject;
using Newtonsoft.Json;

namespace CUE4Parse.UE4.Assets.Exports.Verse;

public class UVerseClass : UClass
{
    public EVerseClassFlags SolClassFlags;

    public override void Deserialize(FAssetArchive Ar, long validPos)
    {
        base.Deserialize(Ar, validPos);
        SolClassFlags = (EVerseClassFlags)GetOrDefault<uint>(nameof(SolClassFlags));
    }

    protected internal override void WriteJson(JsonWriter writer, JsonSerializer serializer)
    {
        base.WriteJson(writer, serializer);
        writer.WritePropertyName(nameof(SolClassFlags));
        serializer.Serialize(writer, SolClassFlags);
    }
}

[JsonConverter(typeof(EnumConverter<EVerseClassFlags>))]
public enum EVerseClassFlags : uint
{
	None                            = 0x00000000u,
	NativeBound                     = 0x00000001u,
	UniversallyAccessible           = 0x00000002u, // The class is accessible from any Verse path, and is in a package with a public scope.
	Concrete                        = 0x00000004u, // The class can be instantiated without explicitly setting any properties
	Module                          = 0x00000008u, // This class represents a Verse module
	UHTNative                       = 0x00000010u, // This class was created by UHT
	Tuple                           = 0x00000020u, // This class represents a tuple
	EpicInternal                    = 0x00000040u, // This class is epic_internal
	HasInstancedSemantics           = 0x00000080u, // This class is using explicit instanced reference semantics (backcompat)
	FinalSuper                      = 0x00000100u, // This class has a <final_super> attribute
	Castable                        = 0x00000200u, // This class has a <castable> attribute
	EpicInternalConstructor         = 0x00000400u, // This class's constructor is epic_internal
	Persistable                     = 0x00000800u, // This class has a <persistable> attribute
	Parametric                      = 0x00001000u, // This class definition is local to a function, i.e. is parametric
	InternalCodegen                 = 0x00002000u, // This class is generated by the compiler for internal purposes and not represent any user-defined class.
	PersonaConstructible            = 0x00004000u, // This class may be constructed by Persona
	HasVar                          = 0x00008000u, // This class has at least one mutable variable.  (Not needed in new VM)
	InheritsFromBlueprint           = 0x00010000u, // This class has a blueprint class as (transitive) superclass
	HasTransientSubobjects          = 0x00020000u, // This class has a non-serialized reference to an archetype instantiation
	HasFieldAttribute               = 0x00040000u, // This class or a superclass uses the @field attribute

	Err_Inoperable                  = 0x40000000u, // One or more of the class's functions contain mis-linked (malformed) bytecode
	Err_Incomplete                  = 0x80000000u, // The class layout is malformed (missing super, illformed data-member, etc.)

	Err = (Err_Incomplete | Err_Inoperable)
}
