name: Tests

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-linux:
    name: tests-linux
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Run Release tests
        run: dotnet test CUE4Parse.Tests/CUE4Parse.Tests.csproj --configuration Release --logger "console;verbosity=normal"
